# Generated by Django 5.0.4 on 2024-04-23 08:54

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0002_alter_careers_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careers',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, populate_from='job_title', unique=True),
        ),
    ]
