# Generated by Django 5.0.4 on 2024-04-23 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0004_category_rename_image_careers_company_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='careers',
            name='job_type',
            field=models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('freelance', 'Freelance'), ('internship', 'Internship'), ('temporary', 'Temporary')], default='full_time', max_length=20, verbose_name='Job Type'),
        ),
    ]
