# Generated by Django 5.0.4 on 2024-04-29 09:55

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0005_careers_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careers',
            name='company_logo',
            field=models.ImageField(upload_to='careerimage/', verbose_name='Company Logo *'),
        ),
        migrations.AlterField(
            model_name='careers',
            name='descriptions',
            field=ckeditor.fields.RichTextField(verbose_name='Job Descriptions(responsibility,qualification) *'),
        ),
        migrations.AlterField(
            model_name='careers',
            name='job_title',
            field=models.CharField(max_length=150, verbose_name='Job Title *'),
        ),
        migrations.AlterField(
            model_name='careers',
            name='job_type',
            field=models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('freelance', 'Freelance'), ('internship', 'Internship'), ('temporary', 'Temporary')], default='full_time', max_length=20, verbose_name='Job Type *'),
        ),
        migrations.AlterField(
            model_name='careers',
            name='location',
            field=models.CharField(max_length=150, verbose_name='Location *'),
        ),
        migrations.AlterField(
            model_name='careers',
            name='salary',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Salary *'),
        ),
        migrations.AlterField(
            model_name='careers',
            name='valid_date',
            field=models.DateField(verbose_name='Valid Date *'),
        ),
    ]
