# Generated by Django 5.0.4 on 2024-04-21 10:35

import autoslug.fields
import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(choices=[('news', 'News'), ('insights', 'Insights'), ('case_studies', 'Case Studies')], default='news', max_length=150, verbose_name='Select Resource Type')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('image', models.ImageField(upload_to='resourcesimage/', verbose_name='Select Image')),
                ('descriptions', ckeditor.fields.RichTextField(verbose_name='Descriptions')),
                ('slug', autoslug.fields.AutoSlugField(default=None, editable=False, populate_from='title', unique=True)),
            ],
            options={
                'verbose_name': 'Resources',
                'verbose_name_plural': 'Resources',
                'ordering': ['id'],
            },
        ),
    ]
