# Generated by Django 5.0.4 on 2024-04-21 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bannar_image', models.ImageField(upload_to='bannerimage/')),
            ],
        ),
    ]
