# Generated by Django 5.0.4 on 2024-04-21 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solutions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_image', models.ImageField(upload_to='solutionimages/', verbose_name='Solution Icon Image')),
                ('image', models.ImageField(upload_to='solutionimages/', verbose_name='Solution Main Image')),
                ('title', models.CharField(max_length=150, verbose_name='Solution Name')),
                ('descriptions', models.TextField(verbose_name='Enter your descriptions')),
            ],
            options={
                'verbose_name': 'Solution',
                'verbose_name_plural': 'Solutions',
                'ordering': ['-id'],
            },
        ),
    ]
