# Generated by Django 5.0.4 on 2024-04-21 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_solutions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solutions',
            options={'ordering': ['id'], 'verbose_name': 'Solution', 'verbose_name_plural': 'Solutions'},
        ),
        migrations.AddField(
            model_name='solutions',
            name='short_descriptions',
            field=models.TextField(default=1, max_length=300, verbose_name='Enter short descriptions'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='solutions',
            name='descriptions',
            field=models.TextField(verbose_name='Enter descriptions'),
        ),
    ]
