# Generated by Django 5.0.4 on 2024-04-21 08:21

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_solutions_options_solutions_short_descriptions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_image', models.ImageField(upload_to='sectorsicon/', verbose_name='Choose Icon Image')),
                ('title', models.CharField(max_length=150, verbose_name='Enter Title')),
                ('descriptions', models.TextField(verbose_name='Enter descriptions')),
                ('slug', autoslug.fields.AutoSlugField(default=None, editable=False, populate_from='title', unique=True)),
            ],
        ),
    ]
