# Generated by Django 5.0.4 on 2024-04-21 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_sector'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=150, verbose_name='Enter Country')),
                ('logo', models.ImageField(upload_to='logo/')),
                ('company_name', models.CharField(max_length=150)),
                ('post_box', models.CharField(blank=True, max_length=150, null=True, verbose_name='Enter Post Box Number')),
                ('postal_code', models.CharField(blank=True, max_length=150, null=True, verbose_name='Enter Postal Code')),
                ('address', models.CharField(max_length=150, verbose_name='Enter Address')),
                ('office_hours', models.DateTimeField(verbose_name='Select Office Hours')),
                ('phone_number', models.CharField(max_length=150, verbose_name='Enter Phone Number')),
                ('map_image', models.ImageField(upload_to='mapimage/', verbose_name='Please Upload map image like jpb,png')),
                ('map_url', models.URLField(blank=True, null=True, verbose_name='Google Map Url')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='sector',
            options={'ordering': ['id'], 'verbose_name': 'Sector', 'verbose_name_plural': 'Sectors'},
        ),
    ]
