# Generated by Django 5.0.4 on 2024-04-21 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_location_alter_sector_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='office_hours',
            field=models.CharField(max_length=150, verbose_name='Select Enter Office Hours'),
        ),
    ]
