# Generated by Django 5.0.4 on 2024-04-21 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_location_office_hours'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_logo', models.ImageField(upload_to='clientlogo/', verbose_name='Clent Logo')),
            ],
        ),
    ]
