# Generated by Django 5.0.4 on 2024-04-22 05:56

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_testimonials'),
    ]

    operations = [
        migrations.AddField(
            model_name='solutions',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, populate_from='title', unique=True),
        ),
    ]
