# Generated by Django 5.0.4 on 2024-04-22 06:04

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_solutions_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sector',
            name='descriptions',
            field=ckeditor.fields.RichTextField(verbose_name='Enter descriptions'),
        ),
        migrations.AlterField(
            model_name='solutions',
            name='descriptions',
            field=ckeditor.fields.RichTextField(verbose_name='Enter descriptions'),
        ),
    ]
