# Generated by Django 5.0.4 on 2024-04-22 06:16

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_sector_descriptions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bannar_image', models.ImageField(blank=True, null=True, upload_to='bannarimage/', verbose_name='Bannar Image')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('descriptions', ckeditor.fields.RichTextField(verbose_name='Descriptions')),
            ],
        ),
        migrations.AddField(
            model_name='solutions',
            name='solution',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='soltions_types', to='app.aboutsolution'),
            preserve_default=False,
        ),
    ]
