# Generated by Django 5.0.4 on 2024-04-22 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_aboutsolution_solutions_solution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solutions',
            name='solution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='soltions_types', to='app.aboutsolution'),
        ),
    ]
