# Generated by Django 5.0.4 on 2024-04-22 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_solutions_solution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solutions',
            name='solution',
        ),
    ]
