# Generated by Django 5.0.4 on 2024-04-22 08:44

import autoslug.fields
import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_solutions_solution'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolutionSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_category_name', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='solutionimages/', verbose_name=' Main Image')),
                ('descriptions', ckeditor.fields.RichTextField(verbose_name='Enter descriptions')),
                ('slug', autoslug.fields.AutoSlugField(default=None, editable=False, populate_from='sub_category_name', unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solution_sub_category', to='app.solutions')),
            ],
        ),
    ]
