# Generated by Django 5.0.4 on 2024-04-22 08:47

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_solutionsubcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='solutionsubcategory',
            name='short_descriptions',
            field=ckeditor.fields.RichTextField(default=1, verbose_name='Short Descriptions'),
            preserve_default=False,
        ),
    ]
