# Generated by Django 5.0.4 on 2024-04-23 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_aboutsector'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='image',
            field=models.ImageField(default=1, upload_to='sectorimage/'),
            preserve_default=False,
        ),
    ]
