# Generated by Django 5.0.4 on 2024-04-23 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_sector_short_descriptions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_name', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='', verbose_name='Office Image')),
                ('descriptions', models.TextField(max_length=200, verbose_name='Short Description About Office Maximum 200 characters ')),
                ('map_url', models.URLField(verbose_name='Map URL')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
