# Generated by Django 5.0.4 on 2024-04-23 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_office_logo_alter_office_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='image',
            field=models.ImageField(upload_to='Office Image/', verbose_name='Office Image'),
        ),
    ]
