# Generated by Django 5.0.4 on 2024-04-29 09:14

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_office_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='descriptions',
            field=ckeditor.fields.RichTextField(max_length=200, verbose_name='Short Description About Office Maximum 200 characters '),
        ),
    ]
