# Generated by Django 5.0.4 on 2024-04-29 09:55

import autoslug.fields
import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_office_descriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutsector',
            name='descriptions',
            field=ckeditor.fields.RichTextField(verbose_name='Enter Descriptions * '),
        ),
        migrations.AlterField(
            model_name='aboutsector',
            name='image',
            field=models.ImageField(upload_to='sectorimage/', verbose_name='Select Image * '),
        ),
        migrations.AlterField(
            model_name='aboutsector',
            name='short_descriptions',
            field=ckeditor.fields.RichTextField(verbose_name='Enter Short Descriptions * '),
        ),
        migrations.AlterField(
            model_name='aboutsector',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Title * '),
        ),
        migrations.AlterField(
            model_name='aboutsolution',
            name='bannar_image',
            field=models.ImageField(blank=True, null=True, upload_to='bannarimage/', verbose_name='Bannar Image *'),
        ),
        migrations.AlterField(
            model_name='aboutsolution',
            name='descriptions',
            field=ckeditor.fields.RichTextField(verbose_name='Descriptions *'),
        ),
        migrations.AlterField(
            model_name='aboutsolution',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Title *'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='bannar_image',
            field=models.ImageField(upload_to='bannerimage/', verbose_name='Select Banner Image *'),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_logo',
            field=models.ImageField(upload_to='clientlogo/', verbose_name='Clent Logo *'),
        ),
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.CharField(max_length=150, verbose_name='Enter Address * '),
        ),
        migrations.AlterField(
            model_name='location',
            name='company_name',
            field=models.CharField(max_length=150, verbose_name='Enter Company Name * '),
        ),
        migrations.AlterField(
            model_name='location',
            name='country',
            field=models.CharField(max_length=150, verbose_name='Enter Country * '),
        ),
        migrations.AlterField(
            model_name='location',
            name='logo',
            field=models.ImageField(upload_to='logo/', verbose_name='Select Logo * '),
        ),
        migrations.AlterField(
            model_name='location',
            name='map_image',
            field=models.ImageField(upload_to='mapimage/', verbose_name='Please Upload map image like jpb,png * '),
        ),
        migrations.AlterField(
            model_name='location',
            name='map_url',
            field=models.URLField(blank=True, null=True, verbose_name='Google Map Url * '),
        ),
        migrations.AlterField(
            model_name='location',
            name='office_hours',
            field=models.CharField(max_length=150, verbose_name='Select Office Hours * '),
        ),
        migrations.AlterField(
            model_name='location',
            name='phone_number',
            field=models.CharField(max_length=150, verbose_name='Enter Phone Number * '),
        ),
        migrations.AlterField(
            model_name='office',
            name='descriptions',
            field=ckeditor.fields.RichTextField(max_length=200, verbose_name='Short Description About Office Maximum 200 characters  *'),
        ),
        migrations.AlterField(
            model_name='office',
            name='image',
            field=models.ImageField(upload_to='Office Image/', verbose_name='Office Image *'),
        ),
        migrations.AlterField(
            model_name='office',
            name='logo',
            field=models.ImageField(upload_to='Office Image/', verbose_name='Office Logo *'),
        ),
        migrations.AlterField(
            model_name='office',
            name='map_url',
            field=models.URLField(verbose_name='Map URL *'),
        ),
        migrations.AlterField(
            model_name='office',
            name='office_name',
            field=models.CharField(max_length=150, verbose_name='Office Name *'),
        ),
        migrations.AlterField(
            model_name='sector',
            name='descriptions',
            field=ckeditor.fields.RichTextField(verbose_name='Enter descriptions * '),
        ),
        migrations.AlterField(
            model_name='sector',
            name='icon_image',
            field=models.ImageField(upload_to='sectorsicon/', verbose_name='Choose Icon Image * '),
        ),
        migrations.AlterField(
            model_name='sector',
            name='image',
            field=models.ImageField(upload_to='sectorimage/', verbose_name='Select Image * '),
        ),
        migrations.AlterField(
            model_name='sector',
            name='short_descriptions',
            field=ckeditor.fields.RichTextField(max_length=500, verbose_name='Short Description *'),
        ),
        migrations.AlterField(
            model_name='sector',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Enter Title * '),
        ),
        migrations.AlterField(
            model_name='solutions',
            name='descriptions',
            field=ckeditor.fields.RichTextField(verbose_name='Enter descriptions *'),
        ),
        migrations.AlterField(
            model_name='solutions',
            name='icon_image',
            field=models.ImageField(upload_to='solutionimages/', verbose_name='Solution Icon Image *'),
        ),
        migrations.AlterField(
            model_name='solutions',
            name='image',
            field=models.ImageField(upload_to='solutionimages/', verbose_name='Solution Main Image *'),
        ),
        migrations.AlterField(
            model_name='solutions',
            name='short_descriptions',
            field=models.TextField(max_length=300, verbose_name='Enter short descriptions *'),
        ),
        migrations.AlterField(
            model_name='solutions',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Solution Name *'),
        ),
        migrations.AlterField(
            model_name='solutionsubcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solution_sub_category', to='app.solutions', verbose_name='Select Category *'),
        ),
        migrations.AlterField(
            model_name='solutionsubcategory',
            name='descriptions',
            field=ckeditor.fields.RichTextField(verbose_name='Descriptions *'),
        ),
        migrations.AlterField(
            model_name='solutionsubcategory',
            name='image',
            field=models.ImageField(upload_to='solutionimages/', verbose_name='Select Main Image *'),
        ),
        migrations.AlterField(
            model_name='solutionsubcategory',
            name='short_descriptions',
            field=ckeditor.fields.RichTextField(verbose_name='Short Descriptions *'),
        ),
        migrations.AlterField(
            model_name='solutionsubcategory',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, populate_from='sub_category_name *', unique=True),
        ),
        migrations.AlterField(
            model_name='solutionsubcategory',
            name='sub_category_name',
            field=models.CharField(max_length=150, verbose_name='Sub Category Name *'),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='descriptions',
            field=models.TextField(verbose_name='Enter Descriptions *'),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='image',
            field=models.ImageField(upload_to='testimonialsimage/', verbose_name='Select Image *'),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Enter Name *'),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='position',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Enter Position'),
        ),
    ]
