# Generated by Django 5.0.4 on 2024-04-30 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_aboutsector_descriptions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssocialtedCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=150, verbose_name='Company Name')),
                ('website_url', models.URLField(verbose_name='Company Website URL')),
                ('company_logo', models.ImageField(upload_to='associatedlogo/', verbose_name='Associated Company Logo')),
            ],
        ),
    ]
