# Generated by Django 5.0.4 on 2024-04-24 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='short_descriptions',
            field=models.TextField(default=1, verbose_name='About Short Descriptions'),
            preserve_default=False,
        ),
    ]
