# Generated by Django 5.0.4 on 2024-04-24 04:55

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_about_short_descriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='short_descriptions',
            field=ckeditor.fields.RichTextField(verbose_name='About Short Descriptions'),
        ),
    ]
