# Generated by Django 5.0.4 on 2024-04-24 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_organizationsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsetting',
            name='location',
            field=models.CharField(default=1, max_length=200, verbose_name='Organizaton Location'),
            preserve_default=False,
        ),
    ]
